### ISSUE TITLE
davfs.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by str0k3** [fentas/docker-volume-davfs#3]
Hi, i'm trying to install your plugin in docker running on openmediavault. Unfortunatelly I get this error. Any ideas what am I doing wrong or what causes the problem?

sudo docker plugin install fentas/davfs
Plugin "fentas/davfs" is requesting the following privileges:
network: [host]
mount: [/var/lib/docker/plugins/]
device: [/dev/fuse]
capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from fentas/davfs
60a0c44b5ea4: Download complete
Digest: sha256:623bd2f914267f83eaba03591cbebc4517b2d3bedcc28f70b25c239e6931f356
Status: Downloaded newer image for fentas/davfs:latest
Error response from daemon: dial unix /run/docker/plugins/104207cac63af708387d043260b67c1b785a8d425bae896ac97400d29c1ab50c/davfs.sock: connect: no such file or directory

**Comment by fentas** [comment]
Have you tried to uninstall it completely before reinstalling?

```
docker plugin rm fentas/davfs:latest
```

**Comment by fentas** [comment]
I updated the plugin config file. Maybe this will resolve your issue.
If not feel free to reopen the issue.

**Comment by empwilli** [comment]
It seems like that resolved the issue. Can you please upload a new build of the plugin?

I've been searching for an hour now until I found this issue (and tried to build the project myself in parallel). Thanks for the great work, btw!

**Comment by raphaelyancey** [comment]
Same issue here, but reinstalling it didn't solve the problem. Any other guess?

**Comment by SuperSandro2000** [comment]
same problem here

**Comment by fentas** [comment]
Could you check the following?

The error message you get includes the plugin id
`/run/docker/plugins/104207cac63af708387d043260b67c1b785a8d425bae896ac97400d29c1ab50c[ <-- plugin id]/davfs.so`. 
Does it differ from plugin id `docker plugin list --no-trunc` ?
Also  if there is a folder with `davfs.sock`? (within bash `ls /run/docker/plugins/*/davfs.sock`)

**Comment by SuperSandro2000** [comment]
````
$ docker plugin list --no-trunc
ID                                                                 NAME                  DESCRIPTION               ENABLED
04a1dc29ea2c86d75b1eb2eed6e3e22c2b816d177b867addfa3e8c4091bb56f3   fentas/davfs:latest  
   davfs plugin for Docker   false
$ sudo ls /run/docker/plugins/04a1dc29ea2c86d75b1eb2eed6e3e22c2b816d177b867addfa3e8c4091bb56f3/
ls: cannot access '/run/docker/plugins/04a1dc29ea2c86d75b1eb2eed6e3e22c2b816d177b867addfa3e8c4091bb56f3/': No such file or directory
````

Creating the folder and enabling the plugin does not work and the folder gets deleted.

**Comment by fentas** [comment]
@vieux sorry to drag you into this but maybe you have already encountered this kind of problem by any chance as the codebase is more or less the same to sshfs.

I'll try to reproduce this behavior in the next weeks.

**Comment by SuperSandro2000** [comment]
FYI I tried this on armhf/Rpi3b and no plugins work their.. x86/amd64 works like a charm.

**Comment by fentas** [comment]
Seems we are not alone with this issue (see the referenced issue).
Anyone still having this or found a solution?

**Comment by TomerFi** [comment]
I'm having the same issue.
Running `raspbian9-stretch` on `rpi3b` with `docker engine 18.09` as swarm worker.
Failing while trying to enable the `vieux/sshfs:1.4` plugin:
```
Error response from daemon: dial unix /run/docker/plugins/**/sshfs.sock: connect: no such file or directory
```

**Comment by ilmtr** [comment]
Same problem here, Rpi3
